input_data_path: data/persuade_2/persuade_2.0_human_scores_demo_id_github.csv
base_model_path: meta-llama/Meta-Llama-3-8B
adapter_path: models/sft_llama3_8b/last
max_num_tokens: 768
output_dir: data/scaling/llama3_8b
n_examples: 1024
n_gen_per_prompt: 2
