input_data_path: data/persuade_2/persuade_2.0_human_scores_demo_id_github.csv
base_model_path: tiiuae/falcon-7b
adapter_path: models/sft_falcon/last
max_num_tokens: 1024
output_dir: data/scaling/falcon_7b
n_examples: 256
n_gen_per_prompt: 2


